import { useState } from 'react';
import { Plus, Trash2, Repeat2 } from 'lucide-react';
import type { FinanceData, RecurringFrequency, RecurringTransaction } from '../types/finance';
import { euro } from '../utils/finance';
import { frequencyLabel, monthlyEquivalent } from '../utils/planning';
export function Recurring({data,setData}:{data:FinanceData;setData:(d:FinanceData)=>void}){
 const [open,setOpen]=useState(false),[type,setType]=useState<'income'|'expense'>('expense'),[frequency,setFrequency]=useState<RecurringFrequency>('monthly');
 const add=(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget),startDate=String(f.get('startDate'));const item:RecurringTransaction={id:crypto.randomUUID(),type,description:String(f.get('description')),amount:Number(f.get('amount')),frequency,startDate,dayOfMonth:['monthly','quarterly','yearly'].includes(frequency)?new Date(startDate+'T12:00:00').getDate():undefined,accountId:String(f.get('accountId')),categoryId:String(f.get('categoryId')),active:true,fixedCost:f.get('fixedCost')==='on'};setData({...data,recurringTransactions:[...data.recurringTransactions,item]});setOpen(false)};
 const remove=(id:string)=>setData({...data,recurringTransactions:data.recurringTransactions.filter(r=>r.id!==id)}),toggle=(id:string)=>setData({...data,recurringTransactions:data.recurringTransactions.map(r=>r.id===id?{...r,active:!r.active}:r)});
 const fixed=data.recurringTransactions.filter(r=>r.type==='expense'&&r.fixedCost&&r.active).reduce((s,r)=>s+monthlyEquivalent(r),0),cats=data.categories.filter(c=>c.type===type);
 const dateLabel=(r:RecurringTransaction)=>r.startDate?new Date(r.startDate+'T12:00:00').toLocaleDateString('nl-NL',{weekday:'long',day:'numeric',month:'short'}):`dag ${r.dayOfMonth||1}`;
 return <><header className="with-action"><div><p className="eyebrow">Planning</p><h1>Terugkerend</h1><p className="muted">Beheer salaris, vaste lasten en andere terugkerende transacties.</p></div><button className="primary" onClick={()=>setOpen(!open)}><Plus size={18}/>Toevoegen</button></header>
 <div className="stats recurring-stats"><article><div className="icon"><Repeat2/></div><span>Vaste lasten gemiddeld per maand</span><b>{euro(fixed)}</b><small>{euro(fixed*12)} per jaar</small></article></div>
 {open&&<form className="card form" onSubmit={add}><select value={type} onChange={e=>setType(e.target.value as 'income'|'expense')}><option value="expense">Uitgave</option><option value="income">Inkomst</option></select><input name="description" placeholder="Omschrijving" required/><input name="amount" type="number" min="0.01" step="0.01" placeholder="Bedrag" required/><select value={frequency} onChange={e=>setFrequency(e.target.value as RecurringFrequency)}><option value="weekly">Wekelijks</option><option value="biweekly">Elke 2 weken</option><option value="fourweekly">Elke 4 weken</option><option value="monthly">Maandelijks</option><option value="quarterly">Per kwartaal</option><option value="yearly">Jaarlijks</option></select><label className="field-label">Eerste datum<input name="startDate" type="date" required/></label><select name="categoryId" required defaultValue=""><option value="" disabled>{cats.length ? 'Kies een categorie' : `Geen categorieën voor ${type === 'income' ? 'inkomsten' : 'uitgaven'}`}</option>{cats.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><select name="accountId" required defaultValue=""><option value="" disabled>{data.accounts.length ? 'Kies een rekening' : 'Maak eerst een rekening aan'}</option>{data.accounts.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select>{type==='expense'&&<label className="check-line"><input type="checkbox" name="fixedCost"/> Dit is een vaste last</label>}<button className="primary">Opslaan</button></form>}
 <section className="card">{data.recurringTransactions.length===0?<div className="empty">Nog geen terugkerende transacties.</div>:data.recurringTransactions.map(r=><div className="row" key={r.id}><div><b>{r.description}</b><small>{frequencyLabel(r.frequency)} · {dateLabel(r)} · {r.fixedCost?'Vaste last · ':''}{r.active?'Actief':'Gepauzeerd'}</small></div><div className="amount-actions"><strong className={r.type}>{r.type==='income'?'+ ':'- '}{euro(r.amount)}</strong><button className="secondary compact" onClick={()=>toggle(r.id)}>{r.active?'Pauze':'Activeer'}</button><button className="icon-button" onClick={()=>remove(r.id)}><Trash2 size={17}/></button></div></div>)}</section></>;
}
