import { useState } from 'react';
import { Plus, Pencil, Trash2 } from 'lucide-react';
import type { FinanceData, SavingsGoal } from '../types/finance';
import { accountBalance, euro } from '../utils/finance';
import { Modal } from '../components/ui/Modal';
export function SavingsGoals({data,setData}:{data:FinanceData;setData:(d:FinanceData)=>void}){
 const [open,setOpen]=useState(false);const [editing,setEditing]=useState<SavingsGoal|null>(null);
 const add=(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);const goal:SavingsGoal={id:editing?.id??crypto.randomUUID(),name:String(f.get('name')),targetAmount:Number(f.get('target')),currentAmount:Number(f.get('current')||0),targetDate:String(f.get('date')||''),accountId:String(f.get('accountId')||'')||undefined};setData({...data,savingsGoals:editing?data.savingsGoals.map(g=>g.id===editing.id?goal:g):[...data.savingsGoals,goal]});setOpen(false);setEditing(null)};
 const edit=(g:SavingsGoal)=>{setEditing(g);setOpen(true)};const del=(id:string)=>confirm('Spaardoel verwijderen?')&&setData({...data,savingsGoals:data.savingsGoals.filter(g=>g.id!==id)});
 const savingsAccounts=data.accounts.filter(a=>a.type==='savings');
 const allocated=(accountId:string)=>data.savingsGoals.filter(g=>g.accountId===accountId).reduce((s,g)=>s+g.currentAmount,0);
 return <><header className="with-action"><div><p className="eyebrow">Doelen</p><h1>Spaardoelen</h1><p className="muted">Koppel doelen aan je spaarrekening en voorkom dubbel tellen.</p></div><button className="primary" onClick={()=>{setEditing(null);setOpen(!open)}}><Plus size={18}/>Spaardoel</button></header>
 {savingsAccounts.map(a=><section className="card allocation" key={a.id}><div><b>{a.name}</b><small>Saldo {euro(accountBalance(data,a.id))}</small></div><div><span>Toegewezen {euro(allocated(a.id))}</span><strong>Vrij {euro(accountBalance(data,a.id)-allocated(a.id))}</strong></div></section>)}
 <Modal open={open} title={editing?'Spaardoel bewerken':'Spaardoel toevoegen'} onClose={()=>{setOpen(false);setEditing(null)}}><form className="form modal-form" onSubmit={add}><input name="name" placeholder="Bijv. Vakantie" defaultValue={editing?.name} required/><input name="target" type="number" step="0.01" placeholder="Doelbedrag" defaultValue={editing?.targetAmount} required/><input name="current" type="number" step="0.01" placeholder="Al gespaard" defaultValue={editing?.currentAmount}/><input name="date" type="date" defaultValue={editing?.targetDate}/><select name="accountId" defaultValue={editing?.accountId??''}><option value="">Niet gekoppeld</option>{savingsAccounts.map(a=><option value={a.id} key={a.id}>{a.name}</option>)}</select><button className="primary">{editing?'Wijzigingen opslaan':'Opslaan'}</button></form></Modal>
 <div className="goal-grid">{data.savingsGoals.map(g=>{const p=Math.min(100,Math.round(g.currentAmount/g.targetAmount*100));return <article className="card" key={g.id}><div className="goal-card-actions"><h2>{g.name}</h2><div><button className="icon-button" onClick={()=>edit(g)}><Pencil size={17}/></button><button className="icon-button" onClick={()=>del(g.id)}><Trash2 size={17}/></button></div></div><strong className="goal-amount">{euro(g.currentAmount)}</strong><p className="muted">van {euro(g.targetAmount)}</p><div className="progress"><i style={{width:p+'%'}}/></div><p>{p}% behaald{g.accountId?` · ${data.accounts.find(a=>a.id===g.accountId)?.name??''}`:''}</p></article>})}</div></>}
